server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbm_db_test01?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

    #jackson
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
#mybatis实体映射
mybatis:
  type-aliases-package: com.example.springbootmybatis.entity

logging:
  level:
    com.example.springbootmybatis.mapper: debug
  path: /springbootmybatis_log/
